DROP TABLE IF EXISTS COMPONENT_DATA_ARRAY
;
DROP TABLE IF EXISTS COMPONENT_DATA
;
DROP TABLE IF EXISTS COMPONENT
;

CREATE TABLE COMPONENT_DATA_ARRAY
(
	TABLE_KEY NUMERIC(9) NOT NULL,
	COMPONENT_DATA NUMERIC(9),
	DATA_TYPE VARCHAR(10),
	DATA_DATA DATETIME,
	DATA_NUMBER NUMERIC(10,2),
	DATA_VARCHAR VARCHAR(255),
	DATA_TEXT TEXT,
	DATA_URL VARCHAR(255),
	PRIMARY KEY (TABLE_KEY),
	KEY (COMPONENT_DATA)
) 
;


CREATE TABLE COMPONENT_DATA
(
	TABLE_KEY NUMERIC(9) NOT NULL,
	COMPONENT NUMERIC(9) NOT NULL,
	DATA_NAME VARCHAR(50) NOT NULL,
	DATA_TYPE VARCHAR(10),
	DATA_DATE DATETIME,
	DATA_NUMBER NUMERIC(10,2),
	DATA_VARCHAR VARCHAR(255),
	DATA_TEXT TEXT,
	DATA_URL VARCHAR(255),
	DATA_ARRAY NUMERIC(1),
	PRIMARY KEY (TABLE_KEY),
	KEY (COMPONENT)
) 
;


CREATE TABLE COMPONENT
(
	TABLE_KEY NUMERIC(9) NOT NULL,
	NAME VARCHAR(125) NOT NULL,
	EJBNAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (TABLE_KEY)
) 
;





ALTER TABLE COMPONENT_DATA_ARRAY ADD CONSTRAINT FK_DATA_COMPONENT_ARRAY_COMPONENT_DATA 
	FOREIGN KEY (COMPONENT_DATA) REFERENCES COMPONENT_DATA (TABLE_KEY)
;

ALTER TABLE COMPONENT_DATA ADD CONSTRAINT FK_COMPONENT_DATA_COMPONENT 
	FOREIGN KEY (COMPONENT) REFERENCES COMPONENT (TABLE_KEY)
;
