DROP TABLE IF EXISTS PARAMETERS
;
CREATE TABLE PARAMETERS
(
	TABLE_KEY VARCHAR(50) NOT NULL,
	DOMAIN NUMERIC(5) NOT NULL,
	DATA_DATE DATETIME,
	DATA_NUMBER NUMERIC(10,2),
	DATA_VARCHAR VARCHAR(255),
	PRIMARY KEY (TABLE_KEY, DOMAIN)
) 
;


