DROP TABLE IF EXISTS USER
;
CREATE TABLE USER
(
	TABLE_KEY VARCHAR(50) NOT NULL,
	DOMAIN NUMERIC(5) NOT NULL,
	USER_NAME VARCHAR(50),
	USER_PASSWORD VARCHAR(50) NOT NULL,
	IS_ADMIN NUMERIC(1) NOT NULL DEFAULT 0,
	DATE_START DATE NOT NULL,
	DATE_END DATE,
	PRIMARY KEY (TABLE_KEY),
	KEY (DOMAIN)
) 
;


ALTER TABLE USER ADD CONSTRAINT FK_USER_DOMAIN 
	FOREIGN KEY (DOMAIN) REFERENCES DOMAIN (TABLE_KEY)
;

