DROP TABLE IF EXISTS USER_BY_SECTION
;
CREATE TABLE USER_BY_SECTION
(
	USER_SEC VARCHAR(50) NOT NULL,
	SECTION NUMERIC(5) NOT NULL,
	PRIMARY KEY (USER_SEC, SECTION),
	KEY (USER_SEC)
) 
;


ALTER TABLE USER_BY_SECTION ADD CONSTRAINT FK_USER_BY_SECTION_USER 
	FOREIGN KEY (USER_SEC) REFERENCES USER (TABLE_KEY)
;

